/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nyte;

import java.util.Random;

/**
 *
 * @author vitorlofonseca
 */
public class dialogo extends javax.swing.JFrame {

    /**
     * Creates new form dialogo
     */
    public dialogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDado = new javax.swing.JLabel();
        lancarDado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(null);

        lblDado.setFont(new java.awt.Font("Cantarell", 1, 72)); // NOI18N
        lblDado.setText("-");
        lblDado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDado.setAlignmentY(0.2F);
        getContentPane().add(lblDado);
        lblDado.setBounds(820, 40, 130, 80);

        lancarDado.setText("Lançar Dado");
        lancarDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancarDadoActionPerformed(evt);
            }
        });
        getContentPane().add(lancarDado);
        lancarDado.setBounds(820, 140, 130, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lancarDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancarDadoActionPerformed
             
        Random random = new Random();
        int resultDado = random.nextInt(6)+1;
        
        //impressão do resultado
        lblDado.setText(Integer.toString(resultDado));
    }//GEN-LAST:event_lancarDadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dialogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lancarDado;
    private javax.swing.JLabel lblDado;
    // End of variables declaration//GEN-END:variables
}
