/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControllerView;

import Model.AreaCorpo;
import Model.Item;
import DAO.AreaCorpoDAO;
import DAO.Connect;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.List;
import java.awt.Point;
import java.security.KeyStore.Entry.Attribute;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vitorlofonseca
 */
public class AdmGerenciaItem extends javax.swing.JFrame {

    /**
     * Criação de item
     */
    public AdmGerenciaItem(Connection conn) throws SQLException, ClassNotFoundException {
        initComponents();
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
        
        HashMap areasCorpo = AreaCorpoDAO.getAreasCorpo();
        
        int i=0;
        String[] areasString = new String[areasCorpo.size()];
        
        //iterando no mapa de itens
        for (Iterator it = areasCorpo.entrySet().iterator(); it.hasNext();) {
            
            Map.Entry<Integer, AreaCorpo> areaCorpo = (Map.Entry<Integer, AreaCorpo>) it.next();
            
            areasString[i] = areaCorpo.getValue().getAreaCorpo();
            i++;
        }
        
        areaCorporal.setModel(new javax.swing.DefaultComboBoxModel<>(areasString));
    }
    
    /**
     * Edição de item
     */
    public AdmGerenciaItem(Item item, Connection conn) throws SQLException, ClassNotFoundException {
        initComponents();
        
        nomeItem.setText(item.getNome());
        valorItem.setText(Float.toString(item.getValor()));
        
        tituloTela.setText(item.getNome());
        
        HashMap areasCorpo = AreaCorpoDAO.getAreasCorpo();
        
        int i=0;
        String[] areasString = new String[areasCorpo.size()];
        
        //iterando no mapa de itens
        for (Iterator it = areasCorpo.entrySet().iterator(); it.hasNext();) {
            
            Map.Entry<Integer, AreaCorpo> areaCorpo = (Map.Entry<Integer, AreaCorpo>) it.next();
            
            areasString[i] = areaCorpo.getValue().getAreaCorpo();
            i++;
        }
        
        areaCorporal.setModel(new javax.swing.DefaultComboBoxModel<>(areasString));
        
        areaCorporal.setSelectedItem(item.getAreaCorpo().getAreaCorpo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloTela = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeItem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valorItem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        areaCorporal = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        tituloTela.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        tituloTela.setText("Cadastro Item");
        getContentPane().add(tituloTela);
        tituloTela.setBounds(40, 10, 320, 25);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 50, 15);

        nomeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeItemActionPerformed(evt);
            }
        });
        getContentPane().add(nomeItem);
        nomeItem.setBounds(180, 70, 165, 25);

        jLabel3.setText("Área Corporal");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 100, 110, 15);

        valorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorItemActionPerformed(evt);
            }
        });
        getContentPane().add(valorItem);
        valorItem.setBounds(180, 130, 165, 25);

        jLabel4.setText("Valor");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 130, 80, 15);

        areaCorporal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(areaCorporal);
        areaCorporal.setBounds(180, 100, 165, 25);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 200, 185, 25);

        jLabel5.setText("Negociação");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 200, 100, 15);

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel6.setText("Combate");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 170, 76, 19);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(160, 230, 185, 25);

        jLabel7.setText("Defesa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 230, 70, 15);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(160, 260, 185, 25);

        jLabel8.setText("Dano");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 260, 70, 15);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(160, 290, 185, 25);

        jLabel9.setText("Fuga");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 290, 60, 15);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(60, 360, 122, 40);

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(230, 360, 122, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeItemActionPerformed

    private void valorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorItemActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmGerenciaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmGerenciaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmGerenciaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmGerenciaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Connection conn = null;
                try {
                    conn = Connect.conectar();
                } catch (SQLException ex) {
                    Logger.getLogger(AdmGerenciaItens.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdmGerenciaItem.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    new AdmGerenciaItem(conn).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdmGerenciaItem.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdmGerenciaItem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> areaCorporal;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nomeItem;
    private javax.swing.JLabel tituloTela;
    private javax.swing.JTextField valorItem;
    // End of variables declaration//GEN-END:variables
}
