/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControllerView;

import DAO.ItemDAO;
import DAO.SalvarDAO;
import Model.Item;
import Model.SaveGame;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author vitorlofonseca
 */
public class CarregarJogo extends javax.swing.JFrame {

    private HashMap saves;
    /**
     * Creates new form CarregarJogo
     */
    public CarregarJogo() throws SQLException, ClassNotFoundException {
        initComponents();
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
        
        this.saves = SalvarDAO.getSaves();        
        String[] savesString = new String[this.saves.size()];
        
        int i=0;
        
        //iterando no mapa de itens
        for (Iterator it = this.saves.entrySet().iterator(); it.hasNext();) {
            Map.Entry<Integer, SaveGame> item = (Map.Entry<Integer, SaveGame>) it.next();
            savesString[i] = item.getValue().getNome();
            i++;
        }
        
        //lista de itens
        listaJogosSalvos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = savesString;
            public int getSize() { return savesString.length; }
            public String getElementAt(int i) { return savesString[i]; }
        });
        
        
        listaJogosSalvos.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                JList list = (JList)evt.getSource();
                if (evt.getClickCount() == 2) {
                    int index = list.locationToIndex(evt.getPoint());
                    
                    SaveGame save = null;
                    try {
                        save = SalvarDAO.getSaveGamePorNome(listaJogosSalvos.getSelectedValue());
                    } catch (SQLException ex) {
                        Logger.getLogger(CarregarJogo.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(CarregarJogo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    
                    MenuIntermediario telaMenu = null;
                    telaMenu = new MenuIntermediario(save.getId());
                    MenuIntermediario.idPersonagem = save.getJogador().getPersonagem().getId();
                    MenuIntermediario.idSaveGame = save.getId();
                    TelaDialogo.idDialogo = save.getDialogoCheckpoint().getId();
                                       
                    telaMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    telaMenu.setVisible(true);
        
                }
            }
        });
    
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaJogosSalvos = new javax.swing.JList<String>();
        jLabel25 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 440));
        setResizable(false);
        getContentPane().setLayout(null);

        listaJogosSalvos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaJogosSalvos.setName("listaJogosSalvos"); // NOI18N
        jScrollPane1.setViewportView(listaJogosSalvos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 550, 250);

        jLabel25.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        jLabel25.setText("Load Game");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(40, -10, 550, 90);

        btnVoltar.setText("Back");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(610, 150, 140, 50);

        jButton1.setText("Load");
        jButton1.setName("loadBtn"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 90, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaInicial telaInicial = new TelaInicial();
        this.setVisible(false);
        telaInicial.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        SaveGame save = null;
        try {
            save = SalvarDAO.getSaveGamePorNome(listaJogosSalvos.getSelectedValue());
        } catch (SQLException ex) {
            Logger.getLogger(CarregarJogo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CarregarJogo.class.getName()).log(Level.SEVERE, null, ex);
        }


        MenuIntermediario telaMenu = null;
        telaMenu = new MenuIntermediario(save.getId());
        MenuIntermediario.idPersonagem = save.getJogador().getPersonagem().getId();
        MenuIntermediario.idSaveGame = save.getId();
        TelaDialogo.idDialogo = save.getDialogoCheckpoint().getId();

        telaMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        telaMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarregarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarregarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarregarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarregarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CarregarJogo().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CarregarJogo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CarregarJogo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaJogosSalvos;
    // End of variables declaration//GEN-END:variables
}
