/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControllerView;

import DAO.PersonagemDAO;
import Model.Personagem;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vitorlofonseca
 */
public class MenuIntermediario extends javax.swing.JFrame {

    public static int idPersonagem = 2;
    
    /**
     * Creates new form MenuIntermediario
     */
    public MenuIntermediario() {
        initComponents();
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSalvarJogo = new javax.swing.JButton();
        btnArmario = new javax.swing.JButton();
        btnTelaInicial = new javax.swing.JButton();
        btnGerenciaItens = new javax.swing.JButton();
        btnDialogo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 325));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bem Vindo! ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 10, 400, 50);

        btnSalvarJogo.setText("Salvar Jogo");
        btnSalvarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarJogoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarJogo);
        btnSalvarJogo.setBounds(370, 90, 150, 40);

        btnArmario.setText("Taverna");
        btnArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArmarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnArmario);
        btnArmario.setBounds(30, 220, 150, 40);

        btnTelaInicial.setText("Voltar Menu");
        btnTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaInicial);
        btnTelaInicial.setBounds(370, 220, 150, 40);

        btnGerenciaItens.setText("Equipamentos");
        btnGerenciaItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciaItensActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerenciaItens);
        btnGerenciaItens.setBounds(30, 90, 150, 40);

        btnDialogo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDialogo.setText("Jornada!");
        btnDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDialogo);
        btnDialogo.setBounds(190, 150, 170, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cidade.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogoActionPerformed
        TelaDialogo dialogo = null;
        try {
            dialogo = new TelaDialogo();
        } catch (SQLException ex) {
            Logger.getLogger(MenuIntermediario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuIntermediario.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialogo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDialogoActionPerformed

    private void btnTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialActionPerformed
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaInicialActionPerformed

    private void btnGerenciaItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciaItensActionPerformed
        GerenciaItens gerenciaItens;
        try {
            gerenciaItens = new GerenciaItens();
            gerenciaItens.setVisible(true);
        this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuIntermediario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuIntermediario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGerenciaItensActionPerformed

    private void btnArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArmarioActionPerformed
        Taverna taverna;
        try {
            taverna = new Taverna();
            taverna.setVisible(true);
            taverna.setCaller("MenuIntermediario");
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuIntermediario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuIntermediario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnArmarioActionPerformed

    private void btnSalvarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarJogoActionPerformed
        SalvarJogo salvarJogo = new SalvarJogo();
        salvarJogo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalvarJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuIntermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuIntermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuIntermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuIntermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuIntermediario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArmario;
    private javax.swing.JButton btnDialogo;
    private javax.swing.JButton btnGerenciaItens;
    private javax.swing.JButton btnSalvarJogo;
    private javax.swing.JButton btnTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
