/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControllerView;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author vitorlofonseca
 */
public class NovoJogo extends javax.swing.JFrame {

    /**
     * Creates new form NovoJogo
     */
    public NovoJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panelEspecializacoes = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jSpinner9 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jSpinner10 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jSpinner11 = new javax.swing.JSpinner();
        panel2 = new java.awt.Panel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        panelEspecializacoes1 = new java.awt.Panel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();
        jSpinner15 = new javax.swing.JSpinner();
        jSpinner16 = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnVoltarTelaInicial = new javax.swing.JToggleButton();
        jLabel25 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        panelEspecializacoes.setLayout(null);

        jLabel1.setText("Agilidade");
        panelEspecializacoes.add(jLabel1);
        jLabel1.setBounds(10, 50, 58, 15);

        jLabel2.setText("Conhecimento");
        panelEspecializacoes.add(jLabel2);
        jLabel2.setBounds(10, 80, 110, 15);

        jLabel3.setText("Blefe");
        panelEspecializacoes.add(jLabel3);
        jLabel3.setBounds(10, 110, 80, 15);

        jLabel4.setText("Força");
        panelEspecializacoes.add(jLabel4);
        jLabel4.setBounds(10, 140, 100, 15);

        jLabel5.setText("Furtividade");
        panelEspecializacoes.add(jLabel5);
        jLabel5.setBounds(10, 170, 100, 15);

        jLabel11.setText("Inteligência");
        panelEspecializacoes.add(jLabel11);
        jLabel11.setBounds(10, 200, 90, 15);

        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel13.setText("Especializações");
        panelEspecializacoes.add(jLabel13);
        jLabel13.setBounds(20, 10, 180, 20);
        panelEspecializacoes.add(jSpinner1);
        jSpinner1.setBounds(120, 200, 60, 26);

        jLabel14.setText("Restantes:");
        panelEspecializacoes.add(jLabel14);
        jLabel14.setBounds(200, 150, 80, 15);
        panelEspecializacoes.add(jSpinner2);
        jSpinner2.setBounds(120, 50, 60, 26);
        panelEspecializacoes.add(jSpinner3);
        jSpinner3.setBounds(120, 80, 60, 26);
        panelEspecializacoes.add(jSpinner4);
        jSpinner4.setBounds(120, 110, 60, 26);
        panelEspecializacoes.add(jSpinner5);
        jSpinner5.setBounds(120, 140, 60, 26);
        panelEspecializacoes.add(jSpinner6);
        jSpinner6.setBounds(120, 170, 60, 26);

        jLabel15.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel15.setText("20");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelEspecializacoes.add(jLabel15);
        jLabel15.setBounds(230, 170, 40, 40);

        jLabel16.setText("Lábia");
        panelEspecializacoes.add(jLabel16);
        jLabel16.setBounds(10, 230, 90, 15);
        panelEspecializacoes.add(jSpinner7);
        jSpinner7.setBounds(120, 230, 60, 26);

        jLabel17.setText("Percepção");
        panelEspecializacoes.add(jLabel17);
        jLabel17.setBounds(10, 260, 90, 15);
        panelEspecializacoes.add(jSpinner8);
        jSpinner8.setBounds(120, 260, 60, 26);

        jLabel18.setText("Resistência");
        panelEspecializacoes.add(jLabel18);
        jLabel18.setBounds(10, 290, 90, 15);
        panelEspecializacoes.add(jSpinner9);
        jSpinner9.setBounds(120, 290, 60, 26);

        jLabel19.setText("Sobrevivência");
        panelEspecializacoes.add(jLabel19);
        jLabel19.setBounds(10, 320, 100, 15);
        panelEspecializacoes.add(jSpinner10);
        jSpinner10.setBounds(120, 320, 60, 26);

        jLabel20.setText("Vontade");
        panelEspecializacoes.add(jLabel20);
        jLabel20.setBounds(10, 350, 90, 15);
        panelEspecializacoes.add(jSpinner11);
        jSpinner11.setBounds(120, 350, 60, 26);

        getContentPane().add(panelEspecializacoes);
        panelEspecializacoes.setBounds(350, 100, 300, 390);

        panel2.setLayout(null);

        jLabel6.setText("Nome");
        panel2.add(jLabel6);
        jLabel6.setBounds(20, 50, 40, 15);
        panel2.add(jTextField3);
        jTextField3.setBounds(70, 50, 210, 25);
        panel2.add(jTextField6);
        jTextField6.setBounds(70, 90, 210, 25);

        jLabel7.setText("Idade");
        panel2.add(jLabel7);
        jLabel7.setBounds(20, 90, 36, 15);

        jLabel8.setText("Tipo");
        panel2.add(jLabel8);
        jLabel8.setBounds(20, 130, 29, 15);
        panel2.add(jTextField7);
        jTextField7.setBounds(70, 170, 210, 25);

        jLabel9.setText("Altura");
        panel2.add(jLabel9);
        jLabel9.setBounds(20, 180, 39, 15);
        panel2.add(jTextField8);
        jTextField8.setBounds(70, 210, 210, 25);

        jLabel10.setText("Peso");
        panel2.add(jLabel10);
        jLabel10.setBounds(20, 220, 33, 15);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel2.add(jComboBox2);
        jComboBox2.setBounds(70, 130, 210, 25);

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel12.setText("Dados");
        panel2.add(jLabel12);
        jLabel12.setBounds(20, 10, 180, 20);

        getContentPane().add(panel2);
        panel2.setBounds(20, 100, 300, 280);

        panelEspecializacoes1.setLayout(null);

        jLabel21.setText("Agilidade");
        panelEspecializacoes1.add(jLabel21);
        jLabel21.setBounds(10, 50, 58, 15);

        jLabel22.setText("Conhecimento");
        panelEspecializacoes1.add(jLabel22);
        jLabel22.setBounds(10, 90, 110, 15);

        jLabel23.setText("Blefe");
        panelEspecializacoes1.add(jLabel23);
        jLabel23.setBounds(10, 130, 80, 15);

        jLabel24.setText("Força");
        panelEspecializacoes1.add(jLabel24);
        jLabel24.setBounds(10, 170, 100, 15);

        jLabel28.setText("Restantes:");
        panelEspecializacoes1.add(jLabel28);
        jLabel28.setBounds(200, 80, 80, 15);
        panelEspecializacoes1.add(jSpinner13);
        jSpinner13.setBounds(120, 50, 60, 26);
        panelEspecializacoes1.add(jSpinner14);
        jSpinner14.setBounds(120, 90, 60, 26);
        panelEspecializacoes1.add(jSpinner15);
        jSpinner15.setBounds(120, 130, 60, 26);
        panelEspecializacoes1.add(jSpinner16);
        jSpinner16.setBounds(120, 170, 60, 26);

        jLabel29.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel29.setText("20");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelEspecializacoes1.add(jLabel29);
        jLabel29.setBounds(230, 100, 40, 40);

        jLabel35.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel35.setText("Combate");
        panelEspecializacoes1.add(jLabel35);
        jLabel35.setBounds(20, 10, 180, 20);

        getContentPane().add(panelEspecializacoes1);
        panelEspecializacoes1.setBounds(680, 100, 300, 220);

        jToggleButton2.setText("Taverna");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(20, 410, 300, 50);

        jToggleButton1.setText("Salvar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(850, 410, 130, 50);

        btnVoltarTelaInicial.setText("Voltar");
        btnVoltarTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarTelaInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarTelaInicial);
        btnVoltarTelaInicial.setBounds(680, 410, 130, 50);

        jLabel25.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        jLabel25.setText("Novo Personagem");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(40, 0, 550, 90);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/castelo.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1010, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void btnVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTelaInicialActionPerformed
        TelaInicial telaInicial = new TelaInicial();
        this.setVisible(false);
        telaInicial.setVisible(true);
    }//GEN-LAST:event_btnVoltarTelaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnVoltarTelaInicial;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner15;
    private javax.swing.JSpinner jSpinner16;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblBackground;
    private java.awt.Panel panel2;
    private java.awt.Panel panelEspecializacoes;
    private java.awt.Panel panelEspecializacoes1;
    // End of variables declaration//GEN-END:variables
}
